/* GENERATED by scripts/generate-vault-sigils.mjs — do not edit by hand.

   Outer Wilds vault-lock sigils quantised against a subset of the site's
   ASCII ramp (" .,:;irsXA253hMHGS#9B&@"). The petal count is the mode
   index: one for DEEP, two for FLAT, three for CHAR.

   The grid is 21 columns by 11 rows, and .rm-art's font-size is what maps
   that onto a round mark — re-run the script and adjust that rule together. */
export const VAULT_SIGILS = {
  deep: [
    "     sA#&###&#As     ",
    "   A&@@&r   r&@@&A   ",
    " r&A##A#     #A##A&r ",
    "r@s @si##XsX##is@ s@r",
    "##  ##  isXsi  ##  ##",
    "&X   #&s     s&#   X&",
    "##    iA#####Ai    ##",
    "r@s               s@r",
    " r&A             A&r ",
    "   A&Ar       rA&A   ",
    "     sA#######As     ",
  ],
  flat: [
    "     sA#######As     ",
    "   A&#Xri   irX#&A   ",
    " r&@&#AA#@&@#AA#&@&r ",
    "r@@#AX r&AiA&r XA#@@r",
    "#@XrrX&@X   X@&XrrX@#",
    "&A    A@     @A    A&",
    "#@XrrX&@X   X@&XrrX@#",
    "r@@#AX r&AiA&r XA#@@r",
    " r&@&#AA#@&@#AA#&@&r ",
    "   A&#Xri   irX#&A   ",
    "     sA#######As     ",
  ],
  char: [
    "     sA#######As     ",
    "   A&@&##AXA##&@&A   ",
    " r&Ar   r&#&r   rA&r ",
    "r@s     &&A&&     s@r",
    "#@    i&@&&&@&i    @#",
    "&@X  s&@&A A&@&s  X@&",
    "#&##A&r&#&&&#&r&A##&#",
    "r@sr&&###AAA###&&rs@r",
    " r&AA&         &AA&r ",
    "   A&@&s     s&@&A   ",
    "     sA#&###&#As     ",
  ],
} as const;
