/* GENERATED by scripts/generate-vault-sigils.mjs — do not edit by hand.

   Outer Wilds vault-lock sigils quantised against a subset of the site's
   ASCII ramp (" .,:;irsXA253hMHGS#9B&@"). Each is a circle of water with
   ripple sources on its rim; the source count is the mode index: one for
   DEEP, two for FLAT, three for CHAR. Crossing wavefronts sum, so they
   quantise to denser glyphs where they interfere.

   The grid is 25 columns by 13 rows, and .rm-art's font-size is what maps
   that onto a round mark — re-run the script and adjust that rule together. */
export const VAULT_SIGILS = {
  deep: [
    "       s#&&& &&&#s       ",
    "    s##&&#     #&&##s    ",
    "   s#sssss     sssss#s   ",
    "  s#s s  ss   ss  s s#s  ",
    " s s  ss   sss   ss  s s ",
    "ss s   sss     sss   s ss",
    "s  ss    sss sss    ss  s",
    "ss  ss             ss  ss",
    " s   sss         sss   s ",
    "  ss   sssss sssss   ss  ",
    "   ss               ss   ",
    "    ssss         ssss    ",
    "       ssssi issss       ",
  ],
  flat: [
    "       ssssi issss       ",
    "    ssss         ssss    ",
    "   s#sssssss#sssssss#s   ",
    "  ##Ass   ssrss   ssA##  ",
    " &###s s##     ##s s###& ",
    "A&s  ss sss   sss ss  s&A",
    "&A     ss s   s ss     A&",
    "A&s  ss sss   sss ss  s&A",
    " &###s s##     ##s s###& ",
    "  ##Ass   ssrss   ssA##  ",
    "   s#sssssss#sssssss#s   ",
    "    ssss         ssss    ",
    "       ssssi issss       ",
  ],
  char: [
    "       ssssi issss       ",
    "    s### sss sss ###s    ",
    "   &&&#ssssA#Assss#&&&   ",
    "  &&  ss ##   ## ss  &&  ",
    " &#    s ss   ss s    #& ",
    "s&#ssss#s##sss##s#ssss#&s",
    "ss#ssss#s#s   s#s#ssss#ss",
    "ssss ss  s##s##s  ss ssss",
    " s ss#s ss#####ss s#ss s ",
    "  ss s A#sssssss#A s ss  ",
    "   ssssssss   ssssssss   ",
    "    ss####s   s####ss    ",
    "       sA&&& &&&As       ",
  ],
} as const;
